import { SideNavInterface } from '../../interfaces/side-nav.type';

export const ROUTES: SideNavInterface[] = [
    {
        path: '',
        title: 'Dashboard',
        iconType: 'nzIcon',
        iconTheme: 'outline',
        icon: 'dashboard',
        name: 'dashboard',
        submenu: [
            {
                path: '/dashboard/home',
                title: 'Home',
                iconType: 'nzIcon',
                icon: 'home',
                iconTheme: 'outline',
                name: 'home',
                submenu: [],
            },
            // {
            //     path: '/dashboard/incom',
            //     title: 'Incom',
            //     iconType: 'nzIcon',
            //     icon: 'mobile',
            //     iconTheme: 'outline',
            //     name: 'incom',
            //     submenu: [],
            // },
            {
                path: '/dashboard/template',
                title: 'Mail',
                iconType: 'nzIcon',
                icon: 'user',
                iconTheme: 'outline',
                name: 'users',
                submenu: [],
            },
            {
                path: '/dashboard/users',
                title: 'Users',
                iconType: 'nzIcon',
                icon: 'user',
                iconTheme: 'outline',
                name: 'users',
                submenu: [],
            },
            {
                path: '/dashboard/report',
                title: 'Report',
                iconType: 'nzIcon',
                icon: 'book',
                iconTheme: 'outline',
                name: 'report',
                submenu: [],
            },
            {
                path: '/dashboard/payment',
                title: 'Deposit',
                iconType: 'nzIcon',
                icon: 'money-collect',
                iconTheme: 'outline',
                name: 'payment',
                submenu: [],
            },
            {
                path: '/dashboard/withdraw',
                title: 'Withdraw',
                iconType: 'nzIcon',
                icon: 'money-collect',
                iconTheme: 'outline',
                name: 'withdraw',
                submenu: [],
            },
            {
                path: '/dashboard/sms',
                title: 'SMS',
                iconType: 'nzIcon',
                icon: 'money-collect',
                iconTheme: 'outline',
                name: 'sms',
                submenu: [],
            },
            {
                path: '/dashboard/qrcode',
                title: 'VietQr',
                iconType: 'nzIcon',
                icon: 'money-collect',
                iconTheme: 'outline',
                name: 'qrcode',
                submenu: [],
            },
        ]
    },
    {
        path: '',
        title: 'ZNS',
        iconType: 'nzIcon',
        iconTheme: 'outline',
        icon: '/zalo-seeklogo.com',
        name: 'zns',
        submenu: [
            {
                path: '/zns/template',
                title: 'Template',
                iconType: 'nzIcon',
                icon: 'book',
                iconTheme: 'outline',
                name: 'template',
                submenu: [],
            },
            {
                path: '/zns/follower',
                title: 'Follower',
                iconType: 'nzIcon',
                icon: 'send',
                iconTheme: 'outline',
                name: '',
                submenu: [],
            },
            {
                path: '/zns/incom',
                title: 'Incom',
                iconType: 'nzIcon',
                icon: 'mobile',
                iconTheme: 'outline',
                name: '',
                submenu: [],
            },
        ]
    },
    {
        path: '',
        title: 'Report',
        iconType: 'nzIcon',
        iconTheme: 'outline',
        icon: 'money-collect',
        name: 'report',
        submenu: [
            {
                path: '/report/sales',
                title: 'Sales',
                iconType: 'nzIcon',
                icon: 'book',
                iconTheme: 'outline',
                name: 'sales',
                submenu: [],
            },
        ]
    }
]    